### ISSUE TITLE
Error trancoding audio stream to AAC

### ISSUE THREAD

**Issue by sebtatut** [avTranscoder/avTranscoder#235]
I'm having these errors when trying to transcode audio stream to AAC:

**Logger mesage:** 
```
[mp4 @ 0x7fe4282f1800] Delay between the first packet and last packet in the muxing queue is 10007800 > 10000000: forcing output
[mp4 @ 0x7fe4282f1800] Malformed AAC bitstream detected: use the audio bitstream filter 'aac_adtstoasc' to fix it ('-bsf:a aac_adtstoasc' option with ffmpeg)
```

**Stack trace:**
```
java.lang.RuntimeException: Error when writting packet in stream: Operation not permitted
	at org.avtranscoder.avtranscoderJNI.Transcoder_process__SWIG_0(Native Method)
	at org.avtranscoder.Transcoder.process(Transcoder.java:131)
	...
```

**File metadata:**
```json
{
  "format" : [ {
    "bitrate" : "59221111",
    "compatible_brands" : "qt  ",
    "creation_time" : "2013-01-20 11:13:39",
    "duration" : "N/A",
    "filename" : "/home/tse/Downloads/140119609.mov",
    "formatLongName" : "null",
    "formatName" : "mov,mp4,m4a,3gp,3g2,mj2",
    "major_brand" : "qt  ",
    "minor_version" : "537199360",
    "numberOfAttachementStreams" : "0",
    "numberOfAudioStreams" : "1",
    "numberOfDataStreams" : "1",
    "numberOfPrograms" : "0",
    "numberOfStreams" : "3",
    "numberOfSubtitleStreams" : "0",
    "numberOfUnknownStreams" : "0",
    "numberOfVideoStreams" : "1",
    "startTime" : "0"
  } ],
  "video" : [ {
    "bitDepth" : "20",
    "bitRate" : "57800131",
    "bitWiseAcked" : "False",
    "channel_0" : "chromaHeight 0 - bitStep 1",
    "channel_1" : "chromaHeight 1 - bitStep 1",
    "channel_2" : "chromaHeight 2 - bitStep 1",
    "chromaHeight" : "0",
    "chromaSampleLocation" : "unspecified",
    "chromaWidth" : "1",
    "codecId" : "149",
    "codecLongName" : "null",
    "codecName" : "prores",
    "colorComponents" : "YUV",
    "colorPrimaries" : "unspecified",
    "colorRange" : "unspecified",
    "colorTransfert" : "unspecified",
    "colorspace" : "unspecified",
    "creation_time" : "2013-01-20 11:13:39",
    "displayAspectRatio" : "0",
    "dtgActiveFormat" : "0",
    "duration" : "N/A",
    "encoder" : "Apple ProRes 422 (LT)",
    "fieldOrder" : "unknown",
    "fps" : "N/A",
    "gop" : "",
    "gopSize" : "12",
    "handler_name" : "Apple Alias Data Handler",
    "hasAlpha" : "False",
    "hasBFrames" : "False",
    "height" : "806",
    "interlaced " : "False",
    "isBigEndian" : "False",
    "isHardwareAccelerated" : "False",
    "isIndexedColors" : "False",
    "isPlanar" : "True",
    "isPseudoPaletted" : "False",
    "language" : "eng",
    "level" : "-99",
    "maxBitRate" : "0",
    "maxNbBitsInChannels" : "10",
    "minBitRate" : "0",
    "nbComponents" : "3",
    "nbFrame" : "1122",
    "pixelAspectRatio" : "0",
    "pixelFormatName" : "yuv422p10le",
    "pixelName" : "yuv422p10le",
    "profile" : "-99",
    "profileName" : "null",
    "referencesFrames" : "1",
    "rgbPixel" : "False",
    "startTimecode" : "unset",
    "streamId" : "1",
    "streamIndex" : "0",
    "subsampling" : "422",
    "ticksPerFrame" : "1",
    "timeBase" : "0.04",
    "timecode" : "00:00:00:00",
    "topFieldFirst" : "False",
    "width" : "1920"
  } ],
  "audio" : [ {
    "bitRate" : "1411200",
    "channelDescription" : "null",
    "channelLayout" : "stereo",
    "channelName" : "null",
    "codecId" : "65536",
    "codecLongName" : "null",
    "codecName" : "pcm_s16le",
    "creation_time" : "2013-01-20 11:13:39",
    "duration" : "N/A",
    "handler_name" : "Apple Alias Data Handler",
    "language" : "eng",
    "nbChannels" : "2",
    "nbSamples" : "1986264",
    "sampleFormatLongName" : "signed 16 bits",
    "sampleFormatName" : "s16",
    "sampleRate" : "44100",
    "streamId" : "2",
    "streamIndex" : "1",
    "ticksPerFrame" : "1",
    "timeBase" : "2.26757e-05",
    "timecode" : "00:00:00:00"
  } ],
  "data" : [ {
    "codecId" : "0",
    "codecLongName" : "null",
    "codecName" : "null",
    "creation_time" : "2013-01-20 11:16:33",
    "duration" : "N/A",
    "handler_name" : "Apple Alias Data Handler",
    "language" : "eng",
    "streamId" : "3",
    "streamIndex" : "2",
    "timeBase" : "0.04",
    "timecode" : "00:00:00:00"
  } ],
  "subtitle" : [ ],
  "attachement" : [ ],
  "unknown" : [ ]
}
```

**Comment by cchampet** [comment]
May be related to issue #161
